<a href="https://colab.research.google.com/github/JoseFERNAN/ML4AI/blob/main/week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
ls

drive/  sample_data/

In [ ]:
cd drive/MyDrive/Hands-On-Data-Analysis-with-Pandas-2nd-edition/ch_02/data/

/content/drive/MyDrive/Hands-On-Data-Analysis-with-Pandas-2nd-edition/ch_02/data

In [ ]:
df = pd.read_csv("earthquakes.csv")

In [ ]:
df.mag[0:3]

0    1.35
1    1.29
2    3.42
Name: mag, dtype: float64

In [ ]:
df[["title", "mag"]][0:10]

                                               title   mag
0                      M 1.4 - 9km NE of Aguanga, CA  1.35
1                      M 1.3 - 9km NE of Aguanga, CA  1.29
2                      M 3.4 - 8km NE of Aguanga, CA  3.42
3                      M 0.4 - 9km NE of Aguanga, CA  0.44
4                      M 2.2 - 10km NW of Avenal, CA  2.16
5  M 2.6 - 55km ESE of Punta Cana, Dominican Repu...  2.61
6               M 1.7 - 105km W of Talkeetna, Alaska  1.70
7                   M 1.1 - 10km NW of Parkfield, CA  1.13
8                  M 0.9 - 6km NW of The Geysers, CA  0.92
9            M 4.7 - 219km SSE of Saparua, Indonesia  4.70

In [ ]:
df[df.mag >= 7]

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
837,green,4.1,1000haa3,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.763,3.0,14.0,",us1000haa3,pt18283003,at00pgehsk,",7.0,mww,...,",us,pt,at,",reviewed,1539204500290,"M 7.0 - 117km E of Kimbe, Papua New Guinea",1,earthquake,",dyfi,finite-fault,general-text,geoserve,groun...",600.0,1539378744253,https://earthquake.usgs.gov/earthquakes/eventp...
5263,red,8.4,1000h3p4,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.589,18.0,27.0,",us1000h3p4,us1000h4p4,",7.5,mww,...,",us,us,",reviewed,1538128963480,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake,",dyfi,finite-fault,general-text,geoserve,groun...",480.0,1539123134531,https://earthquake.usgs.gov/earthquakes/eventp...

In [ ]:
df.loc[
    df.title.str.contains('Philippines'),
    ['title', 'mag']
]

                                             title  mag
1471      M 4.5 - 39km ESE of Lamitan, Philippines  4.5
1663       M 4.9 - 21km NNE of Cortes, Philippines  4.9
2330      M 4.2 - 11km NNW of Itbayat, Philippines  4.2
2983        M 4.4 - 5km ESE of Aumbay, Philippines  4.4
3069        M 4.5 - 2km NE of Bulusan, Philippines  4.5
3581      M 4.7 - 55km S of Sarangani, Philippines  4.7
4535      M 4.4 - 135km NNW of Davila, Philippines  4.4
4673  M 4.5 - 173km SE of Pondaguitan, Philippines  4.5
5428       M 4.3 - 22km ESE of Padong, Philippines  4.3
5810   M 5.0 - 45km NNE of San Isidro, Philippines  5.0
5811   M 4.7 - 49km N of Santa Monica, Philippines  4.7
5933         M 4.4 - 23km ENE of Lais, Philippines  4.4
6300    M 4.6 - 56km ENE of Barcelona, Philippines  4.6
6756  M 4.5 - 18km NE of General Luna, Philippines  4.5
6787   M 4.8 - 38km NNE of San Isidro, Philippines  4.8
6941   M 4.5 - 38km NNE of San Isidro, Philippines  4.5
7213      M 4.4 - 22km ENE of Itbayat, Philippines  4.4
8624  M 5.1 - 278km SE of Pondaguitan, Philippines  5.1
8653   M 4.2 - 99km SE of Pondaguitan, Philippines  4.2
8729   M 4.0 - 165km E of Pondaguitan, Philippines  4.0
9321        M 4.3 - 19km NE of Cateel, Philippines  4.3

In [ ]:
df.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,",ci,",automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,",ci,",automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,",ci,",automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,",ci,",automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,",nc,",automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...

In [ ]:
df = pd.read_csv(
    'earthquakes.csv',
    usecols=['title', 'mag', 'place']
    )

In [ ]:
df

,mag,place,title
0,1.35,"9km NE of Aguanga, CA","M 1.4 - 9km NE of Aguanga, CA"
1,1.29,"9km NE of Aguanga, CA","M 1.3 - 9km NE of Aguanga, CA"
2,3.42,"8km NE of Aguanga, CA","M 3.4 - 8km NE of Aguanga, CA"
3,0.44,"9km NE of Aguanga, CA","M 0.4 - 9km NE of Aguanga, CA"
4,2.16,"10km NW of Avenal, CA","M 2.2 - 10km NW of Avenal, CA"
...,...,...,...
9327,0.62,"9km ENE of Mammoth Lakes, CA","M 0.6 - 9km ENE of Mammoth Lakes, CA"
9328,1.00,"3km W of Julian, CA","M 1.0 - 3km W of Julian, CA"
9329,2.40,"35km NNE of Hatillo, Puerto Rico","M 2.4 - 35km NNE of Hatillo, Puerto Rico"
9330,1.10,"9km NE of Aguanga, CA","M 1.1 - 9km NE of Aguanga, CA"
9331,0.66,"9km NE of Aguanga, CA","M 0.7 - 9km NE of Aguanga, CA"

In [ ]:
df.head()

    mag                  place                          title
0  1.35  9km NE of Aguanga, CA  M 1.4 - 9km NE of Aguanga, CA
1  1.29  9km NE of Aguanga, CA  M 1.3 - 9km NE of Aguanga, CA
2  3.42  8km NE of Aguanga, CA  M 3.4 - 8km NE of Aguanga, CA
3  0.44  9km NE of Aguanga, CA  M 0.4 - 9km NE of Aguanga, CA
4  2.16  10km NW of Avenal, CA  M 2.2 - 10km NW of Avenal, CA

In [ ]:
df['big_earthquake'] = df.mag > 5

In [ ]:
df.head()

    mag                  place                          title  big_earthquake
0  1.35  9km NE of Aguanga, CA  M 1.4 - 9km NE of Aguanga, CA           False
1  1.29  9km NE of Aguanga, CA  M 1.3 - 9km NE of Aguanga, CA           False
2  3.42  8km NE of Aguanga, CA  M 3.4 - 8km NE of Aguanga, CA           False
3  0.44  9km NE of Aguanga, CA  M 0.4 - 9km NE of Aguanga, CA           False
4  2.16  10km NW of Avenal, CA  M 2.2 - 10km NW of Avenal, CA           False

In [ ]:
df.loc[df.mag > 5]

,mag,place,title,big_earthquake
118,6.7,"262km NW of Ozernovskiy, Russia","M 6.7 - 262km NW of Ozernovskiy, Russia",True
180,5.2,"25km E of Bitung, Indonesia","M 5.2 - 25km E of Bitung, Indonesia",True
226,5.7,"42km WNW of Sola, Vanuatu","M 5.7 - 42km WNW of Sola, Vanuatu",True
227,5.2,"15km WSW of Pisco, Peru","M 5.2 - 15km WSW of Pisco, Peru",True
258,5.1,"236km NNW of Kuril'sk, Russia","M 5.1 - 236km NNW of Kuril'sk, Russia",True
...,...,...,...,...
9175,5.2,"126km N of Dili, East Timor","M 5.2 - 126km N of Dili, East Timor",True
9176,5.2,"90km S of Raoul Island, New Zealand","M 5.2 - 90km S of Raoul Island, New Zealand",True
9211,6.0,Southwest Indian Ridge,M 6.0 - Southwest Indian Ridge,True
9213,5.1,South of Tonga,M 5.1 - South of Tonga,True
9304,5.1,"34km NW of Finschhafen, Papua New Guinea","M 5.1 - 34km NW of Finschhafen, Papua New Guinea",True

In [23]:
ls

earthquakes.csv   parsed.csv  README.md
example_data.csv  quakes.db   tsunamis.csv

In [24]:
import matplotlib.pyplot as plt

In [25]:
plt

In [26]:
phi_data = df[1:10]

In [27]:
phi_data

,mag,place,title,big_earthquake
1,1.29,"9km NE of Aguanga, CA","M 1.3 - 9km NE of Aguanga, CA",False
2,3.42,"8km NE of Aguanga, CA","M 3.4 - 8km NE of Aguanga, CA",False
3,0.44,"9km NE of Aguanga, CA","M 0.4 - 9km NE of Aguanga, CA",False
4,2.16,"10km NW of Avenal, CA","M 2.2 - 10km NW of Avenal, CA",False
5,2.61,"55km ESE of Punta Cana, Dominican Republic","M 2.6 - 55km ESE of Punta Cana, Dominican Repu...",False
6,1.70,"105km W of Talkeetna, Alaska","M 1.7 - 105km W of Talkeetna, Alaska",False
7,1.13,"10km NW of Parkfield, CA","M 1.1 - 10km NW of Parkfield, CA",False
8,0.92,"6km NW of The Geysers, CA","M 0.9 - 6km NW of The Geysers, CA",False
9,4.70,"219km SSE of Saparua, Indonesia","M 4.7 - 219km SSE of Saparua, Indonesia",False

In [28]:
phi_data = df.loc[df.title.str.contains('Philippines')]

In [29]:
phi_data

,mag,place,title,big_earthquake
1471,4.5,"39km ESE of Lamitan, Philippines","M 4.5 - 39km ESE of Lamitan, Philippines",False
1663,4.9,"21km NNE of Cortes, Philippines","M 4.9 - 21km NNE of Cortes, Philippines",False
2330,4.2,"11km NNW of Itbayat, Philippines","M 4.2 - 11km NNW of Itbayat, Philippines",False
2983,4.4,"5km ESE of Aumbay, Philippines","M 4.4 - 5km ESE of Aumbay, Philippines",False
3069,4.5,"2km NE of Bulusan, Philippines","M 4.5 - 2km NE of Bulusan, Philippines",False
3581,4.7,"55km S of Sarangani, Philippines","M 4.7 - 55km S of Sarangani, Philippines",False
4535,4.4,"135km NNW of Davila, Philippines","M 4.4 - 135km NNW of Davila, Philippines",False
4673,4.5,"173km SE of Pondaguitan, Philippines","M 4.5 - 173km SE of Pondaguitan, Philippines",False
5428,4.3,"22km ESE of Padong, Philippines","M 4.3 - 22km ESE of Padong, Philippines",False
5810,5.0,"45km NNE of San Isidro, Philippines","M 5.0 - 45km NNE of San Isidro, Philippines",False
5811,4.7,"49km N of Santa Monica, Philippines","M 4.7 - 49km N of Santa Monica, Philippines",False
5933,4.4,"23km ENE of Lais, Philippines","M 4.4 - 23km ENE of Lais, Philippines",False
6300,4.6,"56km ENE of Barcelona, Philippines","M 4.6 - 56km ENE of Barcelona, Philippines",False
6756,4.5,"18km NE of General Luna, Philippines","M 4.5 - 18km NE of General Luna, Philippines",False
6787,4.8,"38km NNE of San Isidro, Philippines","M 4.8 - 38km NNE of San Isidro, Philippines",False
6941,4.5,"38km NNE of San Isidro, Philippines","M 4.5 - 38km NNE of San Isidro, Philippines",False
7213,4.4,"22km ENE of Itbayat, Philippines","M 4.4 - 22km ENE of Itbayat, Philippines",False
8624,5.1,"278km SE of Pondaguitan, Philippines","M 5.1 - 278km SE of Pondaguitan, Philippines",True
8653,4.2,"99km SE of Pondaguitan, Philippines","M 4.2 - 99km SE of Pondaguitan, Philippines",False
8729,4.0,"165km E of Pondaguitan, Philippines","M 4.0 - 165km E of Pondaguitan, Philippines",False
9321,4.3,"19km NE of Cateel, Philippines","M 4.3 - 19km NE of Cateel, Philippines",False

In [31]:
df.loc[df.title.str.contains('Arizona')]

,mag,place,title,big_earthquake
1062,1.23,"7km SSW of Colorado City, Arizona","M 1.2 - 7km SSW of Colorado City, Arizona",False
3965,0.94,"7km WSW of Colorado City, Arizona","M 0.9 - 7km WSW of Colorado City, Arizona",False

In [40]:
df = pd.read_csv("earthquakes.csv")

In [41]:
df.loc[3:10, ['mag', 'magType', 'type']]

     mag magType        type
3   0.44      ml  earthquake
4   2.16      md  earthquake
5   2.61      md  earthquake
6   1.70      ml  earthquake
7   1.13      md  earthquake
8   0.92      md  earthquake
9   4.70      mb  earthquake
10  0.50      ml  earthquake

In [42]:
df.mag

0       1.35
1       1.29
2       3.42
3       0.44
4       2.16
        ...
9327    0.62
9328    1.00
9329    2.40
9330    1.10
9331    0.66
Name: mag, Length: 9332, dtype: float64

In [47]:
df.mag.sort_values(ascending=False)[0:10]

5263    7.5
837     7.0
4363    6.7
118     6.7
799     6.5
816     6.2
838     6.1
5323    6.1
9211    6.0
862     6.0
Name: mag, dtype: float64

In [48]:
df

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,",ci,",automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,",ci,",automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,",ci,",automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,",ci,",automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,",nc,",automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9327,NaN,NaN,73086771,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.018060,NaN,185.0,",nc73086771,",0.62,md,...,",nc,",reviewed,1537230228060,"M 0.6 - 9km ENE of Mammoth Lakes, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1537285598315,https://earthquake.usgs.gov/earthquakes/eventp...
9328,NaN,NaN,38063967,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.030410,NaN,50.0,",ci38063967,",1.00,ml,...,",ci,",reviewed,1537230135130,"M 1.0 - 3km W of Julian, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1537276800970,https://earthquake.usgs.gov/earthquakes/eventp...
9329,NaN,NaN,2018261000,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.452600,NaN,276.0,",pr2018261000,",2.40,md,...,",pr,",reviewed,1537229908180,"M 2.4 - 35km NNE of Hatillo, Puerto Rico",0,earthquake,",geoserve,origin,phase-data,",-240.0,1537243777410,https://earthquake.usgs.gov/earthquakes/eventp...
9330,NaN,NaN,38063959,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.018650,NaN,61.0,",ci38063959,",1.10,ml,...,",ci,",reviewed,1537229545350,"M 1.1 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537230211640,https://earthquake.usgs.gov/earthquakes/eventp...
9331,NaN,NaN,38063935,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.016980,NaN,39.0,",ci38063935,",0.66,ml,...,",ci,",reviewed,1537228864470,"M 0.7 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537305830770,https://earthquake.usgs.gov/earthquakes/eventp...

In [50]:
df.drop(columns = ['alert'])

,cdi,code,detail,dmin,felt,gap,ids,mag,magType,mmi,...,sources,status,time,title,tsunami,type,types,tz,updated,url
0,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,NaN,...,",ci,",automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...
1,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,NaN,...,",ci,",automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...
2,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,NaN,...,",ci,",automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...
3,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,NaN,...,",ci,",automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...
4,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,NaN,...,",nc,",automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9327,NaN,73086771,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.018060,NaN,185.0,",nc73086771,",0.62,md,NaN,...,",nc,",reviewed,1537230228060,"M 0.6 - 9km ENE of Mammoth Lakes, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1537285598315,https://earthquake.usgs.gov/earthquakes/eventp...
9328,NaN,38063967,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.030410,NaN,50.0,",ci38063967,",1.00,ml,NaN,...,",ci,",reviewed,1537230135130,"M 1.0 - 3km W of Julian, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1537276800970,https://earthquake.usgs.gov/earthquakes/eventp...
9329,NaN,2018261000,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.452600,NaN,276.0,",pr2018261000,",2.40,md,NaN,...,",pr,",reviewed,1537229908180,"M 2.4 - 35km NNE of Hatillo, Puerto Rico",0,earthquake,",geoserve,origin,phase-data,",-240.0,1537243777410,https://earthquake.usgs.gov/earthquakes/eventp...
9330,NaN,38063959,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.018650,NaN,61.0,",ci38063959,",1.10,ml,NaN,...,",ci,",reviewed,1537229545350,"M 1.1 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537230211640,https://earthquake.usgs.gov/earthquakes/eventp...
9331,NaN,38063935,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.016980,NaN,39.0,",ci38063935,",0.66,ml,NaN,...,",ci,",reviewed,1537228864470,"M 0.7 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537305830770,https://earthquake.usgs.gov/earthquakes/eventp...

In [55]:
df = pd.read_csv("earthquakes.csv")

In [56]:
df.drop(columns='alert')

,cdi,code,detail,dmin,felt,gap,ids,mag,magType,mmi,...,sources,status,time,title,tsunami,type,types,tz,updated,url
0,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,NaN,...,",ci,",automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...
1,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,NaN,...,",ci,",automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...
2,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,NaN,...,",ci,",automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...
3,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,NaN,...,",ci,",automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...
4,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,NaN,...,",nc,",automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9327,NaN,73086771,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.018060,NaN,185.0,",nc73086771,",0.62,md,NaN,...,",nc,",reviewed,1537230228060,"M 0.6 - 9km ENE of Mammoth Lakes, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1537285598315,https://earthquake.usgs.gov/earthquakes/eventp...
9328,NaN,38063967,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.030410,NaN,50.0,",ci38063967,",1.00,ml,NaN,...,",ci,",reviewed,1537230135130,"M 1.0 - 3km W of Julian, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1537276800970,https://earthquake.usgs.gov/earthquakes/eventp...
9329,NaN,2018261000,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.452600,NaN,276.0,",pr2018261000,",2.40,md,NaN,...,",pr,",reviewed,1537229908180,"M 2.4 - 35km NNE of Hatillo, Puerto Rico",0,earthquake,",geoserve,origin,phase-data,",-240.0,1537243777410,https://earthquake.usgs.gov/earthquakes/eventp...
9330,NaN,38063959,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.018650,NaN,61.0,",ci38063959,",1.10,ml,NaN,...,",ci,",reviewed,1537229545350,"M 1.1 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537230211640,https://earthquake.usgs.gov/earthquakes/eventp...
9331,NaN,38063935,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.016980,NaN,39.0,",ci38063935,",0.66,ml,NaN,...,",ci,",reviewed,1537228864470,"M 0.7 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537305830770,https://earthquake.usgs.gov/earthquakes/eventp...

In [57]:
df.columns

Index(['alert', 'cdi', 'code', 'detail', 'dmin', 'felt', 'gap', 'ids', 'mag',
       'magType', 'mmi', 'net', 'nst', 'place', 'rms', 'sig', 'sources',
       'status', 'time', 'title', 'tsunami', 'type', 'types', 'tz', 'updated',
       'url'],
      dtype='object')

In [58]:
df

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,",ci,",automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,",ci,",automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,",ci,",automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,",ci,",automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,",nc,",automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9327,NaN,NaN,73086771,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.018060,NaN,185.0,",nc73086771,",0.62,md,...,",nc,",reviewed,1537230228060,"M 0.6 - 9km ENE of Mammoth Lakes, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1537285598315,https://earthquake.usgs.gov/earthquakes/eventp...
9328,NaN,NaN,38063967,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.030410,NaN,50.0,",ci38063967,",1.00,ml,...,",ci,",reviewed,1537230135130,"M 1.0 - 3km W of Julian, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1537276800970,https://earthquake.usgs.gov/earthquakes/eventp...
9329,NaN,NaN,2018261000,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.452600,NaN,276.0,",pr2018261000,",2.40,md,...,",pr,",reviewed,1537229908180,"M 2.4 - 35km NNE of Hatillo, Puerto Rico",0,earthquake,",geoserve,origin,phase-data,",-240.0,1537243777410,https://earthquake.usgs.gov/earthquakes/eventp...
9330,NaN,NaN,38063959,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.018650,NaN,61.0,",ci38063959,",1.10,ml,...,",ci,",reviewed,1537229545350,"M 1.1 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537230211640,https://earthquake.usgs.gov/earthquakes/eventp...
9331,NaN,NaN,38063935,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.016980,NaN,39.0,",ci38063935,",0.66,ml,...,",ci,",reviewed,1537228864470,"M 0.7 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537305830770,https://earthquake.usgs.gov/earthquakes/eventp...

In [59]:
df = df.drop(columns='alert')

In [60]:
df.columns

Index(['cdi', 'code', 'detail', 'dmin', 'felt', 'gap', 'ids', 'mag', 'magType',
       'mmi', 'net', 'nst', 'place', 'rms', 'sig', 'sources', 'status', 'time',
       'title', 'tsunami', 'type', 'types', 'tz', 'updated', 'url'],
      dtype='object')

In [68]:
for col in df.columns: 
  if (col == 'mag' or col == 'magType'):
    print(col)
    df.pop(col)

mag
magType

In [70]:
df = pd.read_csv("earthquakes.csv")

In [74]:
mag_df = pd.Series(df.mag)

In [75]:
magType_df = pd.Series(df.magType)

In [76]:
concat_df = pd.concat(mag_df, magType_df)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  """Entry point for launching an IPython kernel.

TypeError: ignored

In [77]:
for col in df.columns: 
  if (col == 'mag'):
    mag = df.pop(col)

In [78]:
df = pd.read_csv("earthquakes.csv")

SECOND TASK

In [79]:
for col in df.columns: 
  if (col == 'mag'):
    mag = df.pop(col)
  if (col == 'magType'):
    magType = df.pop(col)

pd.concat([mag, magType], axis=1)

       mag magType
0     1.35      ml
1     1.29      ml
2     3.42      ml
3     0.44      ml
4     2.16      md
...    ...     ...
9327  0.62      md
9328  1.00      ml
9329  2.40      md
9330  1.10      ml
9331  0.66      ml

[9332 rows x 2 columns]

In [80]:
df.columns

Index(['alert', 'cdi', 'code', 'detail', 'dmin', 'felt', 'gap', 'ids', 'mmi',
       'net', 'nst', 'place', 'rms', 'sig', 'sources', 'status', 'time',
       'title', 'tsunami', 'type', 'types', 'tz', 'updated', 'url'],
      dtype='object')

In [86]:
df.columns

Index(['alert', 'cdi', 'code', 'detail', 'dmin', 'felt', 'gap', 'ids', 'mmi',
       'net', 'nst', 'place', 'rms', 'sig', 'sources', 'status', 'time',
       'title', 'tsunami', 'type', 'types', 'tz', 'updated', 'url'],
      dtype='object')

In [88]:
for i in range(len(df.columns)):
  if df.columns[i] in ['tsunami', 'url']:
    print(i)

18
23